apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2 # Kubernetes object that ensures there is always a stable set of running pods for a specific workload
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim # name of the persistant volume claim

      containers:
      - name: db
        image: postgres:latest
        imagePullPolicy: Never

        env: 
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_NAME
              optional: false

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER
              optional: false # same as default; "mysecret" must exist and include a key named "DB_USER"

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD
              optional: false

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

        # using volumes to store db data in volumes to make the data independent of the db container
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data" # location to mount in this container (get data from pvc and also store it in the pvc)
            name: pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort # expose random ports on both nodes
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2 # Kubernetes object that ensures there is always a stable set of running pods for a specific workload
  selector:
    matchLabels: # Use these labels to find in selector
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        # container that wait for db service to be created
        - name: wait-for-db
          image: busybox:1.28.4 # For linux commands. This version is compatible with nslookup
          command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done']
      containers:
      - name: myapp
        image: danmadar/node_web:latest
        imagePullPolicy: Never # Will not download the image

        # you can use envFrom secret to store all key-value pairs like in Secret.
        env: 
        - name: NODE_ENV
          value: production

        - name: APP_PORT
          value: "8080"

        - name: DB_HOST
          value: db

        - name: DB_APP_PORT
          value: "5432"

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER
              optional: false

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD
              optional: false

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_NAME
              optional: false

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort # expose random ports on both nodes
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
