apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: danmadar/node_web:latest
        imagePullPolicy: Never # Will not download the image
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

      # - name: db
      #   image: postgres:latest
      #   resources:
      #     limits:
      #       memory: "512Mi"
      #       cpu: "500m"
      #   ports:
      #   - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort # expose random ports on both nodes
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 8080
