# Example of configuration for compose with shared volumes.

# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "8080:8080"
#   db:
#     image: "mysql"
#     environment: 
#       MYSQL_PASSWORD: password
#     volumes:
#       - db-data:/example

# volumes:
#   db-data: