apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      - secretbox:
          keys:
            - name: mykey # this is the name of the key.
              secret: cDJsMnpuOGxxaDFtNjBUaHpGWERmelpiVkRCa2dVS2Y= # this is the value of the key. need to be 32 bytes and base64 encoded
      - identity: {} # no encryption