apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_USER: cG9zdGdyZXNfdXNlcg== # need to be base64 encoded
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  DB_NAME: cG9zdGdyZXNfZGI=

# To encode in python do:
# import base64
# data = base64.b64encode(b'data to be encoded') # encode data
# print(data)
# print(base64.b64decode(data)) # decode data