apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi # 10Gi for gigabyte. see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node. pods on the same node can access the volume.
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
